version: "3.8"
services:
  zerepy:
    image: ruxdoteth/zerepy:zerepy
    container_name: zerepy
    command:
      - /bin/sh
      - -c
      - |
        cd /app
        rm -rf agents
        mkdir agents
        echo "Creating agent config"
        echo ${AGENT_CONFIG} | base64 -d > agents/${AGENT_NAME}.json
        echo ${GENERAL_CONFIG} | base64 -d > agents/general.json
        poetry run gunicorn -w 1 -b 0.0.0.0:3000 serve:app
    environment:
      - ALLORA_API_KEY=${ALLORA_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EternalAI_API_KEY=${EternalAI_API_KEY}
      - EternalAI_API_URL=${EternalAI_API_URL}
      - FARCASTER_MNEMONIC=${FARCASTER_MNEMONIC}
      - HYPERBOLIC_API_KEY=${HYPERBOLIC_API_KEY}
      - GALADRIEL_API_KEY=${GALADRIEL_API_KEY}
      - GALADRIEL_FINE_TUNE_API_KEY=${GALADRIEL_FINE_TUNE_API_KEY}
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_USER_ID=${TWITTER_USER_ID}
      - GOAT_RPC_PROVIDER_URL=${GOAT_RPC_PROVIDER_URL}
      - GOAT_WALLET_PRIVATE_KEY=${GOAT_WALLET_PRIVATE_KEY}
      - SOLANA_PRIVATE_KEY=${SOLANA_PRIVATE_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - JOBS_QUEUE=${JOBS_QUEUE}
      - RESPONSES_QUEUE=${RESPONSES_QUEUE}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - DSTACK_SIMULATOR_ENDPOINT=${DSTACK_SIMULATOR_ENDPOINT}
    ports:
      - "3000:3000"
    networks:
      - zerepy-network
  tappd:
    image: phalanetwork/tappd-simulator:latest
    container_name: tappd
    ports:
      - "8000:8090"
    networks:
      - zerepy-network

  #rabbitmq:
  #  image: "rabbitmq:3-management"
  #  container_name: rabbitmq
  #  ports:
  #    - "5672:5672"   # AMQP port
  #    - "15672:15672" # Management console port (optional)
  #  healthcheck:
  #    test: ["CMD", "rabbitmqctl", "status"]
  #    interval: 10s
  #    timeout: 10s
  #    retries: 5
  #  networks:
  #    - zerepy-network

networks:
  zerepy-network:
    # driver acceptable values:
    driver: bridge
#
# volumes:
#   data:
